apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-app
  namespace: microservices
  labels:
  {{- include "microservices.labels"  .  | nindent 4}}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: microservices-app
  template:
    metadata:
      labels:
        {{- include "microservices.labels"  .  | nindent 8}}
    spec:
      containers:
        - name: microservices-container
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          ports:
            - containerPort: 5000
          resources:
            {{- toYaml .Values.app.resources | nindent 10}}