apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-app
  namespace: microservices
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: microservices-app
  template:
    metadata:
      labels:
        app: microservices-app
    spec:
      containers:
        - name: microservices-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 5000