apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-app
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.app.annotations }}
    "{{ $key }}": "{{ $value }}"
    {{- end }}
  labels:
  {{- include "microservices.labels"  .  | nindent 4}}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: microservices-app
  template:
    metadata:
      labels:
        {{- include "microservices.labels"  .  | nindent 8}}
    spec:
      # If no securityContext is set in Kubernetes, then: Kubernetes runs the container as whatever user is defined in the image.
      # Best Practice: ✔ Set USER in the Dockerfile and ✔ enforce it with Kubernetes securityContext
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        runAsNonRoot: true
      containers:
        - name: microservices-container
          image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12}}
