apiVersion: v1
kind: Service
metadata:
  name: microservices-service
  namespace: microservices
  labels:
  {{- include "microservices.labels"  .  | nindent 4}}
spec:
  type: ClusterIP
  selector:
    app: microservices-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP