namespace: microservices-prod
app:
  env: prod
  replicaCount: 1
  image:
    repository: mohamedsamirebrahim/microservices-python-image
    tag: 1
  resources:
    limits:
      cpu: 5m
      memory: 20Mi
    requests:
      cpu: 5m
      memory: 20Mi
  annotations:
    reloader.stakater.com/auto: "true"

hpa:
  enabled: false

configmap:
  name: my-config
  data:
    APP_ENV: "prod"
    LOG_LEVEL: "info-prod"
    FEATURE_FLAG: "true"