namespace: microservices-dev
app:
  env: dev
  replicaCount: 1
  image:
    repository: mohamedsamirebrahim/microservices-python-image
    tag: dev-15
    name: mohamedsamirebrahim/microservices-python-image
  resources:
    limits:
      cpu: 5m
      memory: 20Mi
    requests:
      cpu: 5m
      memory: 20Mi
hpa:
  enabled: false
