namespace: microservices-dev
app:
  env: dev
  replicaCount: 1
  image:
    repository: mohamedsamirebrahim/microservices-python-image
    tag: dev-15
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 100Mi
  annotations:
    reloader.stakater.com/auto: "true"

hpa:
  enabled: false

configmap:
  name: my-config
  data:
    APP_ENV: "dev"
    LOG_LEVEL: "info-dev"
    FEATURE_FLAG: "true"
