name: gitleaks-secrets-scan
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks-secrets-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: gitleaks-secrets-scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
